#ifndef GLOBALS_H
#define GLOBALS_H

// Enums
typedef enum {
  ROBOT_STATE_INVALID = 0,
  ROBOT_STATE_READING_QR = 1,
  ROBOT_STATE_SEARCHING_FOR_OBJECT = 2,
  ROBOT_STATE_APPROACHING_OBJECT = 3,
  ROBOT_STATE_APPROACHING_GOAL = 4,
  ROBOT_STATE_PLACING_OBJECT = 5
} ROBOT_STATE;

typedef enum {
  ROBOT_STATE_READING_QR_SUBSTATE_INVALID = 0,
  ROBOT_STATE_READING_QR_SUBSTATE_FINDING_WALL = 1,
  ROBOT_STATE_READING_QR_SUBSTATE_FOLLOWING_WALL = 2,
  ROBOT_STATE_READING_QR_SUBSTATE_APPROACHING_QR = 3,
  ROBOT_STATE_READING_QR_SUBSTATE_TAKING_READING = 4
} ROBOT_STATE_READING_QR_SUBSTATE;

typedef enum {
  LASSO_STATE_INVALID = 0,
  LASSO_STATE_DOWN = 1,
  LASSO_STATE_UP = 2,
  LASSO_STATE_WAITING = 3
} LASSO_STATE;

// Global variables
extern ROBOT_STATE gv_robotState;
extern LASSO_STATE gv_lassoState;
extern int gv_stateFinishedSignal;
extern int gv_stateFailedSignal;

#endif
